### ISSUE TITLE
[Contract] APIs tracker

### ISSUE THREAD

**Issue by radulescuandrew** [code4romania/vic#384]
Web: 

- [x] Create template 
- [x] Get one template
- [x] Update template
- [x] Get all templates list 
- [x] Delete template
- [x] Create contract
- [x] #385
- [x] Get many contracts
- [x] Delete contract
- [x] Get contracts statistics 
- [x] Validate contract by ONG
- [x] Sign contract by ONG
- [x] Reject contract by ONG

Mobile:

- [x] Get all contracts for volunteer
- [x] Get one contract for volunteer
- [x] Sign contract by volunteer
- [x] Reject contract by volunteer
- [x] Count pending documents for volunteer

For Later:

- Download all templates
- Download all approved contracts

**Comment by radulescuandrew** [comment]
Closed. Opened #426 for future version.
